language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
before_install:
- sudo apt-get -y install texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: UJ5BI+EgFHMUGuYPpefRIrJK+BCmAIOqDzyccCoeEDAME/xYvMoKlxQCfQk3ykFxsC95r5CCyaJj0QCtQDoFOHwPNtLMXWGUcHUc7Ff8oc66LMjWgacfyHQg58v1Xyefhb5slT/hOWoubpNU4sfOCOK9RB7YdXJJj8/0epKpl/QHzkUQgAA6a7468mFB2SuAm+E0pbAFCRZyYQ+F0JWn9rOg4Lt7139nCryjgBAI4IRqAu4HG27kGVSEJ2gSo0gQZWsUkXdazouQYjWCjJej6gliNBFNGp5YfOM15YdBgUGunjj7SuNLwIj+epAPbCSBw85FVcUZUzpaLIEIEu2Z88rDUXOuPCJ/K3GBK+YFGMro3HIPaqMAY0V2BqcBhYmzSN1A1Ux2ic6BqDYoNJJikjyL58mVIs8kS72gFp8nqGwiHZ9uQbT76WqW447EB+UiJsM3Uc5Knt0IchVNTBu+VXCQUZirsuuT7/ZzyXolVDtdJRffEAwRYaR9qnIi7lRw2a5jaapo6CNbQF45ApblpB30PuWbW9VRxX3n5E/8ejN6rj5DAzXPyeeD/u3Se1KJtzozf6cEAMXvqzR7SsSsZ2UUQZeqK/wubkYQZ+Kl+H8g9Pzy58B4gVXuebKCvStOu59FXhVDG/io1gSB1nHtXHXdOAfh0l8+jJPIM5oz8Zg=
  on:
    tags: true
    repo: tgrandjean/french-invoice-generator
    python: 3.8
